### ISSUE TITLE
Ignore Procfile "web" directive

### ISSUE THREAD

**Issue by pkallberg** [cloud66/starter#11]
We use `custom_web` instead of the `web` directive - this should populate the service command field if available. If not there should be a standard command for Rails apps.

Example (with our [Discourse app](https://github.com/cloud66-samples/discourse)): 

```
---
services:
  web:
    git: git@github.com:cloud66-samples/discourse.git
    git_branch: master
    command: bundle exec rails server -p _env:PORT
    ports:
      - 9292:80:443
    env_vars:
      RAILS_ENV: production
      RACK_ENV: production
  worker:
    git: git@github.com:cloud66-samples/discourse.git
    git_branch: master
    command: bundle exec sidekiq -e _env:RAILS_ENV
    env_vars:
      RAILS_ENV: production
      RACK_ENV: production
databases:
  - postgresql
  - redis
```

Also note that the port attribution is incorrect (should be port 3000).
