### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by LimeBlast** [cloud66/starter#43]
I'm not sure if this is the best place for this, so apologies if not, but I can't make the tool work correctly.

In the first instance, I run the `starter -g dockerfile,service,docker-compose` command, but this just tells me:

```
flag provided but not defined: -g
Usage of starter:
  -branch string
    	template branch in github (default "master")
  -e string
    	set project environment (default "production")
  -overwrite
    	overwrite existing files
  -p string
    	project path
  -templates string
    	location of the templates directory
  -y	do not prompt user
```

So I try again using `starter dockerfile,service,docker-compose`, which seems to have some more joy, allowing me to answer questions about my project, but then fails on:

```
 Failed to write service.yml due to: template: service.yml.template:29:6: executing "service.yml.template" at <.Name>: can't evaluate field Name in type string
```

Which generates the following files:

`Dockerfile`
```
# Generated by Cloud66 Starter
FROM ruby:2.3.1

RUN apt-get update -qq && apt-get install -y build-essential nodejs imagemagick libmagickwand-dev

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ADD Gemfile* $APP_HOME/
RUN bundle install

ADD . $APP_HOME
```

`service.yml`
```
---
services:

##NEWLINE##
  web:
    git_url: git@redacted.git
    git_branch: master
    command: bundle exec puma -p _env:PORT -C ./config/puma.rb
    build_command: /bin/sh -c "RAILS_ENV=_env:RAILS_ENV bundle exec rake db:schema:load"
    deploy_command: /bin/sh -c "RAILS_ENV=_env:RAILS_ENV bundle exec rake db:migrate"
    build_root: .

    ports:
      - container: 3000
        http: 80
        https: 443
        
        
    

    env_vars:
      RAILS_ENV: production
    
      RACK_ENV: production
    

##NEWLINE##
  worker:
    git_url: git@redacted.git
    git_branch: master
    command: bundle exec rake jobs:work
    
    
    build_root: .

    

    env_vars:
      RAILS_ENV: production
    
      RACK_ENV: production
    



##NEWLINE##
databases:
  - 
```

The app in question is a Rails app based off [suspenders](https://github.com/thoughtbot/suspenders).
