### ISSUE TITLE
Service command not being populated

### ISSUE THREAD

**Issue by pkallberg** [cloud66/starter#5]
Command for various services isn't being populated, for example for these two apps:
https://github.com/cloud66-samples/rails-psql-elasticsearch
https://github.com/cloud66-samples/sinatra-postgres-mongo-redis

It adds an empty field:

```
  web:
    git: git@github.com:cloud66-samples/rails-psql-elasticsearch.git
    git_branch: master
    command:
    ports:
      - 9292:80:443
    env_vars:
      RAILS_ENV: production
      RACK_ENV: production
```
