### ISSUE TITLE
Doesn't detect use of ElasticSearch

### ISSUE THREAD

**Issue by pkallberg** [cloud66/starter#6]
Repository contains `tire` gem, and uses Elasticsearch. This isn't added to databases in service config:

```
---
services:

  web:
    git: git@github.com:cloud66-samples/rails-psql-elasticsearch.git
    git_branch: master
    command:
    ports:
      - 9292:80:443
    env_vars:
      RAILS_ENV: production
      RACK_ENV: production

databases:
  - postgresql
```

Perhaps we need to implement similar detection from main app for various gems.
