### ISSUE TITLE
Service command/port for Padrino/Sinatra apps

### ISSUE THREAD

**Issue by pkallberg** [cloud66/starter#7]
The service command/port for Padrino and Sinatra apps is either empty (see #5) or incorrect:

```
---
services:
  web:
    git: git@github.com:cloud66-samples/padrino-mysql-active_record.git
    git_branch: master
    command: bundle exec rack s _env:$RACK_ENV
    ports:
      - 3000:80:443
    env_vars:
      RAILS_ENV: production
      RACK_ENV: production
databases:
  - mysql
```

This app runs on 9292 and uses `rackup` command to start.
